[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EHR Tutorial"
authors = [{name = "CELEHS", email = "xxx@harvard.edu"}]
dynamic = ["version", "description"]
